// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: proto/system/system.proto

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Systems_GetProvinces_FullMethodName = "/system.Systems/GetProvinces"
)

// SystemsClient is the client API for Systems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemsClient interface {
	GetProvinces(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ProvincesResponse, error)
}

type systemsClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemsClient(cc grpc.ClientConnInterface) SystemsClient {
	return &systemsClient{cc}
}

func (c *systemsClient) GetProvinces(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ProvincesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvincesResponse)
	err := c.cc.Invoke(ctx, Systems_GetProvinces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemsServer is the server API for Systems service.
// All implementations must embed UnimplementedSystemsServer
// for forward compatibility.
type SystemsServer interface {
	GetProvinces(context.Context, *Filter) (*ProvincesResponse, error)
	mustEmbedUnimplementedSystemsServer()
}

// UnimplementedSystemsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemsServer struct{}

func (UnimplementedSystemsServer) GetProvinces(context.Context, *Filter) (*ProvincesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvinces not implemented")
}
func (UnimplementedSystemsServer) mustEmbedUnimplementedSystemsServer() {}
func (UnimplementedSystemsServer) testEmbeddedByValue()                 {}

// UnsafeSystemsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemsServer will
// result in compilation errors.
type UnsafeSystemsServer interface {
	mustEmbedUnimplementedSystemsServer()
}

func RegisterSystemsServer(s grpc.ServiceRegistrar, srv SystemsServer) {
	// If the following call pancis, it indicates UnimplementedSystemsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Systems_ServiceDesc, srv)
}

func _Systems_GetProvinces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemsServer).GetProvinces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Systems_GetProvinces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemsServer).GetProvinces(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

// Systems_ServiceDesc is the grpc.ServiceDesc for Systems service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Systems_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.Systems",
	HandlerType: (*SystemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProvinces",
			Handler:    _Systems_GetProvinces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/system/system.proto",
}
