APP:
  NAME: system_service
  ENV: staging
  URL: localhost
  PORT_SERVER: 4442
  PORT_CLIENT: 9992

# todo implementation cors
# ROUTE:
#   METHODS: [GET, POST, PUT, DELETE]
#   HEADERS: [Content-Type, Authorization, Authorization-ID, Accept-Key]
#   ORIGIN: ['*']

DATABASE:
  READ:
    USERNAME: postgres
    PASSWORD: junior34
    URL: host.docker.internal
    PORT: 5001
    DB_NAME: ecommerce_system
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 100
    SSL_MODE: disable 
  WRITE:
    USERNAME: postgres
    PASSWORD: junior34
    URL: host.docker.internal
    PORT: 5001
    DB_NAME: ecommerce_system
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 100
    SSL_MODE: disable

WHATSAPP-API:
  URL: https://gate.whapi.cloud/
  TOKEN: p6eoir7uqTArQAw9ZQmNf700iSpn6IKh

ELASTIC_APM:
  SERVER_URL: http://apm-server:8200
  SERVICE_NAME: system_service
  ENVIRONMENT: staging
  SECRET_TOKEN: ""         # opsional, kalau pakai authentication di APM server
  GLOBAL_LABELS: team=backend,project=ecommerce

# todo implementation resources grpc when resourceexhausted
# GRPC_MAX_CALL_RECEIVE_MESSAGE: "25"
# GRPC_MAX_CALL_SEND_MESSAGE: "25"